// Shared constants for Video Text App

export const LINE_ANIM_MODES = [
  { id: 'characterByChar', label: 'Character by Character' },
  { id: 'wordByWord', label: 'Word by Word' },
  { id: 'lineByLine', label: 'Line by Line' },
  { id: 'frameByFrame', label: 'Frame by Frame (all lines at once)' }
];

export const LINE_ANIM_EFFECTS = [
  { id: 'fadeIn', label: 'Fade In' },
  { id: 'scaleUp', label: 'Scale Up' },
  { id: 'slideUp', label: 'Slide Up' },
  { id: 'slideDown', label: 'Slide Down' },
  { id: 'slideLeft', label: 'Slide From Left' },
  { id: 'slideRight', label: 'Slide From Right' },
  { id: 'zoomIn', label: 'Zoom In' },
  { id: 'zoomOut', label: 'Zoom Out' },
  { id: 'bounceIn', label: 'Bounce In' },
  { id: 'pop', label: 'Pop' },
  { id: 'elasticIn', label: 'Elastic In' },
  { id: 'swingIn', label: 'Swing In' },
  { id: 'dropIn', label: 'Drop In' },
  { id: 'flyIn', label: 'Fly In' },
  { id: 'floatUp', label: 'Float Up' },
  { id: 'pulseIn', label: 'Pulse In' },
  { id: 'blurIn', label: 'Blur In' },
  { id: 'flipIn', label: 'Flip In' },
  { id: 'rotateIn', label: 'Rotate In' },
  { id: 'fadeScale', label: 'Fade + Scale' },
  { id: 'slideZoom', label: 'Slide + Zoom' },
  { id: 'stagger', label: 'Stagger' },
  { id: 'wave', label: 'Wave' },
  { id: 'cascade', label: 'Cascade' },
  { id: 'splitReveal', label: 'Split Reveal' },
  { id: 'curtain', label: 'Curtain' },
  { id: 'glowIn', label: 'Glow In' },
  { id: 'typewriter', label: 'Typewriter' },
  { id: 'reveal', label: 'Reveal' },
  { id: 'zoomSlide', label: 'Zoom + Slide' },
  { id: 'bounceUp', label: 'Bounce Up' },
  { id: 'fadeDown', label: 'Fade Down' },
  { id: 'spinIn', label: 'Spin In' },
  { id: 'blurFade', label: 'Blur Fade' },
  { id: 'expand', label: 'Expand' },
  { id: 'rise', label: 'Rise' },
  { id: 'slideFade', label: 'Slide Fade' },
  { id: 'scalePop', label: 'Scale Pop' }
];

export const VIDEO_MERGE_TRANSITIONS = [
  { id: 'none', label: 'None (Cut)' },
  { id: 'crossfade', label: 'Crossfade' },
  { id: 'fadeBlack', label: 'Fade to Black' },
  { id: 'fadeWhite', label: 'Fade to White' },
  { id: 'wipeLeft', label: 'Wipe Left' },
  { id: 'wipeRight', label: 'Wipe Right' },
  { id: 'wipeUp', label: 'Wipe Up' },
  { id: 'wipeDown', label: 'Wipe Down' },
  { id: 'slideLeft', label: 'Slide Left' },
  { id: 'slideRight', label: 'Slide Right' },
  { id: 'slideUp', label: 'Slide Up' },
  { id: 'slideDown', label: 'Slide Down' },
  { id: 'zoomIn', label: 'Zoom In' },
  { id: 'zoomOut', label: 'Zoom Out' },
  { id: 'pushLeft', label: 'Push Left' },
  { id: 'pushRight', label: 'Push Right' },
  { id: 'pushUp', label: 'Push Up' },
  { id: 'pushDown', label: 'Push Down' },
  { id: 'circleExpand', label: 'Circle Expand' },
  { id: 'circleContract', label: 'Circle Contract' },
  { id: 'splitHorizontal', label: 'Split Horizontal' },
  { id: 'splitVertical', label: 'Split Vertical' },
  { id: 'blurIn', label: 'Blur In' },
  { id: 'pixelate', label: 'Pixelate' },
  { id: 'rotateIn', label: 'Rotate In' },
  { id: 'flipX', label: 'Flip X' },
  { id: 'flipY', label: 'Flip Y' },
  { id: 'dissolve', label: 'Dissolve' },
  { id: 'diamond', label: 'Diamond' },
  { id: 'radial', label: 'Radial Wipe' },
];
