/** Caption design presets — Text tab (13 categories: Word Focus → Gaming & Tech). */

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

const BASE = {
  strokeWidthPx: null,
  boxPaddingPx: null,
  boxCornerRadiusPx: null,
  boxOffsetX: 0,
  boxOffsetY: 0,
  kineticLogic: 'oneWord',
  kineticStartTime: 0,
  kineticDuration: 0.85,
  kineticLoop: false,
  animationStartTime: 0,
  animationDuration: 0.9,
  animationLoop: false,
  popScale: 1,
  fontWeight: 'bold',
  fontSize: 5,
  letterSpacing: 0,
  lineHeight: 1.35,
  textTransform: 'none',
  gradientEnabled: false,
  gradientColors: ['#FFFFFF', '#E8E8E8'],
  wordHighlightEnabled: false,
  wordHighlightMode: 'voiceSync',
  wordHighlightLineOpt: '2',
  wordHighlightScale: 1.35,
  wordHighlightSpeed: 1,
  wordDimInactive: false,
  wordDimScale: 0.55,
  wordDimAlpha: 0.32,
  wordSizeLogic: null,
  wordLayoutLogic: null,
  colorLogic: 'none',
  fontChangeLogic: 'none',
  animationLogic: 'default',
  animationPreset: 'none',
  kineticEffect: 'none',
  contentTextSectionEnabled: false,
  contentLineAnimType: 'fadeIn',
  contentLineRevealMode: 'wordByWord',
  contentLineAnimSpeed: 2.5,
  textBgEnabled: false,
  textBgCategory: 'gradient',
  textBgPatternId: '',
  textBgLogic: 'perFrame',
  textBgOpacity: 0.88,
  shadowEnabled: false,
  shadowColor: '#000000',
  shadowBlur: 8,
  shadowOffsetX: 0,
  shadowOffsetY: 2,
  wordsPerLine: 4,
  linesPerFrame: 0,
}

export function buildCaptionTextPreset(name, categoryId, o = {}) {
  const id = o.id || slug(name)
  const isBox = (o.styleType || BASE.styleType || 'stroke') === 'box'
  const patch = {
    ...BASE,
    captionTextPresetId: id,
    styleType: o.styleType ?? 'stroke',
    color: o.color ?? '#FFFFFF',
    strokeColor: o.strokeColor ?? '#000000',
    strokeOpacity: o.strokeOpacity ?? 1,
    strokeWidthPercent: o.strokeWidthPercent ?? 6,
    bgColor: o.bgColor ?? 'rgba(0,0,0,0.82)',
    bgOpacity: o.bgOpacity ?? (isBox ? 0.88 : 0),
    boxPaddingPercent: o.boxPaddingPercent ?? 38,
    boxCornerRadiusPercent: o.boxCornerRadiusPercent ?? 18,
    fontFamily: o.fontFamily ?? 'Montserrat',
    ...o,
    captionTextPresetId: id,
  }
  if (o._captionSync) patch._captionSync = o._captionSync
  return { id, name, categoryId, patch }
}

const cat = (categoryId, label, items) => ({
  id: categoryId,
  label,
  presets: items.map(([n, o]) => buildCaptionTextPreset(n, categoryId, o)),
})

/** Title typography presets — includes readable style label for UI. */
const typographyCat = (categoryId, label, items) => ({
  id: categoryId,
  label,
  presets: items.map(([name, typographyStyle, o]) => {
    const preset = buildCaptionTextPreset(name, categoryId, o)
    return { ...preset, typographyStyle }
  }),
})

const syncWord = { _captionSync: { granularity: 'word' } }
const syncKaraoke = { _captionSync: { granularity: 'karaoke' } }
const syncLine = { _captionSync: { granularity: 'line' } }

export const CAPTION_TEXT_PRESET_CATEGORIES = [
  cat('word-focus', '1. Word Focus Designs', [
    ['Word By Word Pop', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', kineticEffect: 'scalePop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', kineticLogic: 'oneWord', wordHighlightScale: 1.45, popScale: 1.3, ...syncWord }],
    ['One Word Highlight', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.55, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 8, ...syncWord }],
    ['One Word One Frame', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordsPerLine: 1, linesPerFrame: 1, fontSize: 6, wordHighlightScale: 1.2, ...syncWord }],
    ['Karaoke Reveal', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', color: '#FFE066', strokeColor: '#000000', colorLogic: 'perWord', animationPreset: 'wordByWord', animationLogic: 'wordByWord', ...syncKaraoke }],
    ['Center Focus Word', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: 'center', wordHighlightScale: 1.6, strokeWidthPercent: 9 }],
    ['Last Word Impact', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: 'last', wordHighlightScale: 1.65, fontFamily: 'Impact', color: '#FFD700', strokeWidthPercent: 10 }],
    ['First Word Hero', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: '1', wordHighlightScale: 1.6, colorLogic: 'firstWord', fontChangeLogic: 'firstWord', color: '#FF6B6B' }],
    ['Single Word Background', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', styleType: 'box', bgColor: 'rgba(0,0,0,0.88)', bgOpacity: 0.92, boxPaddingPercent: 28, wordHighlightScale: 1.15, ...syncWord }],
    ['Alternate Word Background', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: 'alternate', styleType: 'box', bgColor: 'rgba(59,130,246,0.85)', bgOpacity: 0.9, wordHighlightScale: 1.1 }],
    ['Every Third Word Highlight', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: 'everyThree', wordHighlightScale: 1.5, color: '#A78BFA', strokeColor: '#1E1B4B' }],
    ['Active Word Large Others Small', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.75, wordDimInactive: true, wordDimScale: 0.62, wordDimAlpha: 0.45, ...syncWord }],
    ['Active Word Bright Others Dim', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.35, wordDimInactive: true, wordDimScale: 0.85, wordDimAlpha: 0.28, color: '#FFFFFF', ...syncWord }],
    ['One Word Huge Rest Tiny', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 2.1, wordDimInactive: true, wordDimScale: 0.48, wordDimAlpha: 0.4, wordSizeLogic: 'tinyRest', ...syncWord }],
    ['Middle Word Hero', { wordHighlightEnabled: true, wordHighlightMode: 'fixedPerLine', wordHighlightLineOpt: 'center', wordHighlightScale: 1.7, fontFamily: 'Bebas Neue', color: '#F97316' }],
    ['Keyword Spotlight', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', shadowEnabled: true, shadowColor: '#FBBF24', shadowBlur: 22, wordHighlightScale: 1.5, color: '#FEF08A', ...syncWord }],
    ['One Word Glow', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', kineticEffect: 'glow', kineticLoop: true, shadowEnabled: true, shadowColor: '#22D3EE', shadowBlur: 20, wordHighlightScale: 1.4, ...syncWord }],
    ['One Word Stroke', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', styleType: 'stroke', strokeWidthPercent: 14, strokeColor: '#000000', wordHighlightScale: 1.35, ...syncWord }],
    ['One Word Shake', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', kineticEffect: 'shake', kineticLoop: true, wordHighlightScale: 1.3, ...syncWord }],
    ['One Word Zoom', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', kineticEffect: 'zoomIn', animationPreset: 'zoomIn', animationLogic: 'wordByWord', wordHighlightScale: 1.55, ...syncWord }],
    ['One Word Color Switch', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', colorLogic: 'perWord', gradientEnabled: true, gradientColors: ['#FF0080', '#00DFD8', '#FFD700'], ...syncWord }],
  ]),
  cat('layout-composition', '2. Layout & Composition Designs', [
    ['Big Small Big', { wordSizeLogic: 'bigSmallBig', animationLogic: 'wordByWord', animationPreset: 'fadeIn', colorLogic: 'none', fontChangeLogic: 'none' }],
    ['Small Big Small', { wordSizeLogic: 'smallBigSmall', animationLogic: 'wordByWord', animationPreset: 'fadeIn' }],
    ['Two Small One Giant', { wordSizeLogic: 'twoSmallOneGiant', animationLogic: 'wordByWord', animationPreset: 'bounceIn', fontFamily: 'Impact' }],
    ['One Giant Two Small', { wordSizeLogic: 'oneGiantTwoSmall', animationLogic: 'wordByWord', animationPreset: 'scaleIn', fontFamily: 'Anton' }],
    ['Staircase Words', { wordSizeLogic: 'staircase', wordLayoutLogic: 'diagonal', animationLogic: 'wordByWord', animationPreset: 'slideUp' }],
    ['Pyramid Text', { wordSizeLogic: 'pyramid', animationLogic: 'wordCenterOut', animationPreset: 'zoomIn', fontFamily: 'Oswald' }],
    ['Growing Words', { wordSizeLogic: 'growing', animationLogic: 'wordByWord', animationPreset: 'grow', kineticEffect: 'scalePop' }],
    ['Shrinking Words', { wordSizeLogic: 'shrinking', animationLogic: 'wordByWordReverse', animationPreset: 'shrink' }],
    ['Wave Size Text', { wordSizeLogic: 'wave', kineticEffect: 'wave', kineticLoop: true, animationLogic: 'wordByWord' }],
    ['Random Scale Burst', { wordSizeLogic: 'randomBurst', animationLogic: 'wordRandom', animationPreset: 'random', kineticEffect: 'random' }],
    ['Word Stack Vertical', { wordsPerLine: 1, lineHeight: 1.85, animationLogic: 'lineByLine', animationPreset: 'slideUp', fontFamily: 'Inter' }],
    ['Split Line Caption', { wordsPerLine: 2, lineHeight: 1.6, animationLogic: 'lineByLine', animationPreset: 'fadeIn', styleType: 'box', bgOpacity: 0.85 }],
    ['Top Bottom Words', { wordLayoutLogic: 'topBottom', wordSizeLogic: 'bigSmallBig', lineHeight: 1.75, animationLogic: 'wordByWord' }],
    ['Left Right Split', { wordLayoutLogic: 'leftRight', wordsPerLine: 3, animationLogic: 'wordByWord', animationPreset: 'sideEntryLeft' }],
    ['Corner Jump Text', { wordLayoutLogic: 'cornerJump', animationLogic: 'wordRandom', animationPreset: 'bounceIn', kineticEffect: 'bounceIn' }],
    ['Floating Blocks', { wordLayoutLogic: 'floatingBlocks', kineticEffect: 'float', kineticLoop: true, animationLogic: 'wordByWord', styleType: 'box', bgColor: 'rgba(15,23,42,0.75)', bgOpacity: 0.88, boxCornerRadiusPercent: 12 }],
    ['Diagonal Caption', { wordLayoutLogic: 'diagonal', wordSizeLogic: 'staircase', animationLogic: 'wordByWord', animationPreset: 'slideUp' }],
    ['Zigzag Layout', { wordLayoutLogic: 'zigzag', animationLogic: 'wordByWord', animationPreset: 'bounceUp', kineticEffect: 'wobble' }],
    ['Cross Layout Text', { wordLayoutLogic: 'cross', wordSizeLogic: 'pyramid', animationLogic: 'wordCenterOut', animationPreset: 'centerPop' }],
    ['Circular Word Flow', { wordLayoutLogic: 'circular', wordSizeLogic: 'wave', animationLogic: 'wordByWord', kineticEffect: 'orbit', kineticLoop: true }],
  ]),
  cat('outline-background', '3. Outline, Background & Highlight Designs', [
    ['Stroke Only Word', { styleType: 'stroke', strokeWidthPercent: 12, strokeColor: '#FFFFFF', color: 'rgba(255,255,255,0.01)', wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', ...syncWord }],
    ['Fill Then Outline', { styleType: 'stroke', strokeWidthPercent: 10, animationPreset: 'blurIn', animationLogic: 'wordByWord', kineticEffect: 'blurIn', color: '#FFFFFF' }],
    ['Outline To Solid', { styleType: 'stroke', strokeWidthPercent: 8, animationPreset: 'fadeIn', animationLogic: 'wordByWord', kineticEffect: 'fadeIn', color: '#FDE68A' }],
    ['Double Stroke Reveal', { styleType: 'stroke', strokeWidthPercent: 14, shadowEnabled: true, shadowColor: '#FFFFFF', shadowBlur: 2, shadowOffsetX: 2, shadowOffsetY: 2, animationPreset: 'lineReveal', animationLogic: 'wordByWord' }],
    ['Neon Outline Pulse', { styleType: 'stroke', color: '#39FF14', strokeColor: '#000000', strokeWidthPercent: 7, shadowEnabled: true, shadowColor: '#39FF14', shadowBlur: 18, kineticEffect: 'neon', kineticLoop: true }],
    ['Shadow Word Focus', { shadowEnabled: true, shadowColor: '#000000', shadowBlur: 16, shadowOffsetY: 4, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.35, ...syncWord }],
    ['Glow On Keyword', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', shadowEnabled: true, shadowColor: '#F472B6', shadowBlur: 24, color: '#FDA4AF', ...syncWord }],
    ['Border Box Word', { styleType: 'box', bgColor: 'rgba(0,0,0,0.9)', bgOpacity: 0.94, boxPaddingPercent: 32, boxCornerRadiusPercent: 6, strokeWidthPercent: 4, strokeColor: '#FFFFFF' }],
    ['Brush Stroke Highlight', { textBgEnabled: true, textBgCategory: 'organic', textBgPatternId: 'org_splatter', textBgLogic: 'perLine', styleType: 'stroke', strokeWidthPercent: 9, color: '#FFFFFF' }],
    ['Marker Effect Word', { styleType: 'box', bgColor: '#FDE047', bgOpacity: 0.92, color: '#000000', boxPaddingPercent: 22, boxCornerRadiusPercent: 4, fontFamily: 'Permanent Marker' }],
    ['Paint Splash Background', { textBgEnabled: true, textBgCategory: 'organic', textBgPatternId: 'org_splatter', textBgOpacity: 0.75, styleType: 'stroke', strokeWidthPercent: 8, color: '#FFFFFF' }],
    ['Highlighter Swipe', { styleType: 'box', bgColor: 'rgba(250,204,21,0.55)', bgOpacity: 0.85, color: '#000000', boxPaddingPercent: 18, boxCornerRadiusPercent: 2, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', ...syncWord }],
    ['Rounded Box Keyword', { styleType: 'box', bgColor: 'rgba(99,102,241,0.9)', bgOpacity: 0.92, boxCornerRadiusPercent: 28, boxPaddingPercent: 30, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', ...syncWord }],
    ['Underline Focus Word', { kineticEffect: 'underline', wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', color: '#FFFFFF', strokeWidthPercent: 5, ...syncWord }],
    ['Dynamic Border Caption', { styleType: 'box', bgColor: 'rgba(0,0,0,0.82)', bgOpacity: 0.9, boxPaddingPercent: 42, kineticEffect: 'glowPulse', kineticLoop: true, animationPreset: 'pulse', animationLogic: 'lineByLine' }],
    ['Glassmorphism Text', { textBgEnabled: true, textBgCategory: 'glass', textBgPatternId: 'glass_white', textBgOpacity: 0.7, styleType: 'stroke', color: '#FFFFFF', strokeWidthPercent: 4, strokeColor: 'rgba(255,255,255,0.5)' }],
    ['Neon Box Caption', { styleType: 'box', bgColor: 'rgba(0,0,0,0.92)', bgOpacity: 0.95, color: '#39FF14', shadowEnabled: true, shadowColor: '#39FF14', shadowBlur: 16, boxCornerRadiusPercent: 8 }],
    ['Liquid Highlight Word', { gradientEnabled: true, gradientColors: ['#667eea', '#764ba2', '#f953c6'], wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.35, ...syncWord }],
    ['Frosted Background Text', { textBgEnabled: true, textBgCategory: 'glass', textBgPatternId: 'glass_blue', textBgOpacity: 0.82, styleType: 'stroke', color: '#E0F2FE', strokeColor: '#0C4A6E', strokeWidthPercent: 5 }],
    ['Ink Stroke Caption', { styleType: 'stroke', strokeWidthPercent: 11, strokeColor: '#0F172A', color: '#F8FAFC', fontFamily: 'Playfair Display', kineticEffect: 'inkSpread', animationPreset: 'typewriter', animationLogic: 'wordByWord' }],
  ]),
  cat('motion-animation', '4. Motion & Animation Designs', [
    ['Typewriter Caption', { kineticEffect: 'typewriter', animationPreset: 'typewriter', animationLogic: 'charByChar', animationDuration: 1.2, fontFamily: 'Courier New', color: '#00FF88' }],
    ['Bounce Every Word', { animationPreset: 'bounceIn', animationLogic: 'wordByWord', kineticEffect: 'scaleBounce', kineticLogic: 'oneWord' }],
    ['Sliding Word Chain', { animationPreset: 'slideRight', animationLogic: 'wordByWord', kineticEffect: 'slideFromLeft', kineticLogic: 'sequential' }],
    ['Rotation Word Pop', { animationPreset: 'rotateIn', animationLogic: 'wordByWord', kineticEffect: 'rotateIn', popScale: 1.2 }],
    ['Shake Impact Word', { kineticEffect: 'shake', kineticLoop: true, animationPreset: 'shake', animationLogic: 'wordByWord', fontFamily: 'Impact', color: '#EF4444' }],
    ['Elastic Text Flow', { animationPreset: 'elasticIn', animationLogic: 'wordByWord', kineticEffect: 'elastic', kineticDuration: 1.1 }],
    ['Zoom Burst Keywords', { animationPreset: 'zoomIn', animationLogic: 'wordCenterOut', kineticEffect: 'scalePop', popScale: 1.5, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', ...syncWord }],
    ['Beat Sync Captions', { kineticEffect: 'pulse', kineticLoop: true, kineticLogic: 'syncBeat', animationPreset: 'pulse', animationLogic: 'wordByWord' }],
    ['Flash Card Words', { animationPreset: 'flipInX', animationLogic: 'wordByWord', kineticEffect: 'flash', styleType: 'box', bgColor: 'rgba(255,255,255,0.95)', bgOpacity: 0.96, color: '#111827' }],
    ['Cinematic Focus Caption', { fontFamily: 'Cinzel', color: '#FDE68A', strokeColor: '#000000', strokeWidthPercent: 6, animationPreset: 'fadeIn', animationLogic: 'lineByLine', letterSpacing: 2, textTransform: 'uppercase', ...syncLine }],
    ['Bounce In Sequence', { animationPreset: 'bounceIn', animationLogic: 'wordByWord', kineticEffect: 'bounceIn', kineticLogic: 'sequential' }],
    ['Wave Motion Text', { kineticEffect: 'wave', kineticLoop: true, animationPreset: 'wave', animationLogic: 'wordByWord' }],
    ['Rolling Word Reveal', { animationPreset: 'rollIn', animationLogic: 'wordByWord', kineticEffect: 'rollOut' }],
    ['Flip Card Caption', { animationPreset: 'flipInY', animationLogic: 'wordByWord', kineticEffect: 'flipY', styleType: 'box', bgColor: 'rgba(30,41,59,0.9)', bgOpacity: 0.92 }],
    ['Pulse Effect Words', { kineticEffect: 'pulse', kineticLoop: true, animationPreset: 'pulse', animationLogic: 'wordByWord' }],
    ['Swing Motion Text', { kineticEffect: 'swing', kineticLoop: true, animationPreset: 'swing', animationLogic: 'wordByWord' }],
    ['Glitch Flash Words', { kineticEffect: 'glitch', kineticLoop: true, animationPreset: 'random', animationLogic: 'wordRandom', fontFamily: 'Rubik Glitch', color: '#22D3EE' }],
    ['Speed Ramp Caption', { animationPreset: 'lightSpeedIn', animationLogic: 'wordByWord', animationDuration: 0.45, kineticEffect: 'zoomIn', kineticDuration: 0.5 }],
    ['Explosion Word Entry', { animationPreset: 'explode', animationLogic: 'wordByWord', kineticEffect: 'explode', popScale: 1.4 }],
    ['Floating Kinetic Text', { kineticEffect: 'float', kineticLoop: true, animationPreset: 'float', animationLogic: 'wordByWord', color: '#C4B5FD' }],
  ]),
  cat('viral-social', '5. Viral Social Media Styles', [
    ['Kinetic Typography Pro', { kineticEffect: 'scalePop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', fontFamily: 'Montserrat', wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.4, ...syncWord }],
    ['Sentence Build Up', { animationPreset: 'wordByWord', animationLogic: 'wordByWord', kineticEffect: 'fadeIn', ...syncKaraoke }],
    ['Word Stack Then Explode', { wordsPerLine: 1, animationPreset: 'explode', animationLogic: 'lineByLine', kineticEffect: 'explode', lineHeight: 1.7 }],
    ['Caption In Chat Bubble', { styleType: 'box', bgColor: 'rgba(37,99,235,0.92)', bgOpacity: 0.94, boxCornerRadiusPercent: 22, boxPaddingPercent: 36, fontFamily: 'Inter', color: '#FFFFFF', positionY: 72 }],
    ['Highlighted Subtitle', { styleType: 'box', bgColor: 'rgba(0,0,0,0.75)', bgOpacity: 0.88, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', color: '#FFFFFF', ...syncWord }],
    ['Search Bar Caption', { styleType: 'box', bgColor: 'rgba(255,255,255,0.95)', bgOpacity: 0.96, color: '#374151', boxCornerRadiusPercent: 24, boxPaddingPercent: 44, fontFamily: 'Roboto', positionY: 14 }],
    ['Notification Style Text', { styleType: 'box', bgColor: 'rgba(255,255,255,0.96)', bgOpacity: 0.98, color: '#111827', boxCornerRadiusPercent: 14, boxPaddingPercent: 32, shadowEnabled: true, shadowBlur: 12, fontFamily: 'Inter', animationPreset: 'slideDown', animationLogic: 'lineByLine' }],
    ['Comic Book Caption', { fontFamily: 'Bangers', color: '#FACC15', strokeColor: '#000000', strokeWidthPercent: 12, styleType: 'stroke', letterSpacing: 1, kineticEffect: 'scalePop' }],
    ['Newspaper Headline Style', { fontFamily: 'Newsreader', color: '#111827', styleType: 'box', bgColor: '#F5F5F4', bgOpacity: 0.96, textTransform: 'uppercase', letterSpacing: 1.5, boxCornerRadiusPercent: 0 }],
    ['AI Generated Subtitle Style', { fontFamily: 'Space Grotesk', color: '#A5F3FC', strokeColor: '#0E7490', strokeWidthPercent: 5, gradientEnabled: true, gradientColors: ['#67E8F9', '#C084FC'], animationPreset: 'blurIn', animationLogic: 'wordByWord' }],
    ['Podcast Caption Style', { fontFamily: 'Merriweather', color: '#F5F5F4', styleType: 'box', bgColor: 'rgba(23,23,23,0.88)', bgOpacity: 0.9, boxPaddingPercent: 34, lineHeight: 1.5 }],
    ['Documentary Subtitle', { fontFamily: 'Helvetica', color: '#E5E7EB', styleType: 'stroke', strokeWidthPercent: 4, strokeColor: '#000000', letterSpacing: 0.5, animationPreset: 'fadeIn', animationLogic: 'lineByLine' }],
    ['Netflix Intro Text', { fontFamily: 'Bebas Neue', color: '#E50914', strokeColor: '#000000', strokeWidthPercent: 3, textTransform: 'uppercase', letterSpacing: 4, animationPreset: 'zoomIn', animationLogic: 'wordByWord', fontSize: 6.5 }],
    ['Luxury Serif Caption', { fontFamily: 'Playfair Display', color: '#FFD700', strokeColor: '#422006', strokeWidthPercent: 4, gradientEnabled: true, gradientColors: ['#FFD700', '#FFF8DC'], letterSpacing: 1 }],
    ['Gaming Stream Caption', { fontFamily: 'Orbitron', color: '#39FF14', strokeColor: '#000000', strokeWidthPercent: 8, shadowEnabled: true, shadowColor: '#39FF14', shadowBlur: 14, kineticEffect: 'glitch', kineticLoop: true }],
    ['Reaction Video Caption', { fontFamily: 'Impact', color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 14, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.55, fontSize: 5.5, ...syncWord }],
    ['Interview Highlight Style', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', styleType: 'box', bgColor: 'rgba(250,204,21,0.88)', bgOpacity: 0.9, color: '#000000', boxPaddingPercent: 20, ...syncWord }],
    ['Motivation Reel Caption', { fontFamily: 'Anton', color: '#FFFFFF', strokeColor: '#DC2626', strokeWidthPercent: 10, textTransform: 'uppercase', kineticEffect: 'scalePop', animationPreset: 'bounceIn', animationLogic: 'wordByWord' }],
    ['Storytelling Subtitle', { fontFamily: 'Lora', color: '#FEF3C7', styleType: 'stroke', strokeWidthPercent: 5, lineHeight: 1.55, animationPreset: 'fadeUp', animationLogic: 'lineByLine' }],
    ['Viral Retention Caption', { wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', kineticEffect: 'scalePop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', fontFamily: 'Montserrat', wordHighlightScale: 1.5, color: '#FFFFFF', strokeWidthPercent: 9, popScale: 1.35, ...syncWord }],
  ]),
  typographyCat('typography-titles', '6. Typography Title Templates', [
    [
      'Cinematic Title',
      'Bold Condensed Serif',
      {
        fontFamily: 'Cinzel',
        fontWeight: 'bold',
        fontSize: 5.8,
        letterSpacing: 3,
        textTransform: 'uppercase',
        lineHeight: 1.2,
        wordsPerLine: 3,
        color: '#F5F5DC',
        strokeColor: '#0F0F0F',
        strokeWidthPercent: 8,
        shadowEnabled: true,
        shadowColor: 'rgba(0,0,0,0.75)',
        shadowBlur: 14,
        shadowOffsetY: 3,
        animationPreset: 'fadeIn',
        animationLogic: 'lineByLine',
        animationDuration: 1.1,
        kineticEffect: 'fadeIn',
        kineticLogic: 'oneLine',
        ...syncLine,
      },
    ],
    [
      'Epic Movie Title',
      'Ultra Bold Cinematic Serif',
      {
        fontFamily: 'Playfair Display',
        fontWeight: '900',
        fontSize: 6.8,
        letterSpacing: 4,
        textTransform: 'uppercase',
        lineHeight: 1.15,
        wordsPerLine: 2,
        color: '#FFD700',
        strokeColor: '#000000',
        strokeWidthPercent: 10,
        shadowEnabled: true,
        shadowColor: 'rgba(255,215,0,0.45)',
        shadowBlur: 20,
        kineticEffect: 'scalePop',
        animationPreset: 'zoomIn',
        animationLogic: 'wordByWord',
        animationDuration: 0.85,
        popScale: 1.25,
        wordHighlightEnabled: true,
        wordHighlightMode: 'voiceSync',
        wordHighlightScale: 1.2,
        ...syncKaraoke,
      },
    ],
    [
      'Modern Intro',
      'Clean Sans Serif',
      {
        fontFamily: 'Inter',
        fontWeight: '500',
        fontSize: 5,
        letterSpacing: 0.6,
        lineHeight: 1.4,
        wordsPerLine: 4,
        color: '#FFFFFF',
        strokeColor: '#111827',
        strokeWidthPercent: 4,
        animationPreset: 'fadeIn',
        animationLogic: 'lineByLine',
        animationDuration: 1,
        kineticEffect: 'fadeSlide',
        kineticLogic: 'oneLine',
        ...syncLine,
      },
    ],
    [
      'Minimal Title',
      'Thin Sans Serif',
      {
        fontFamily: 'Inter',
        fontWeight: '300',
        fontSize: 4.8,
        letterSpacing: 2.2,
        lineHeight: 1.45,
        wordsPerLine: 4,
        color: '#F9FAFB',
        strokeColor: '#374151',
        strokeWidthPercent: 3,
        strokeOpacity: 0.85,
        animationPreset: 'fadeIn',
        animationLogic: 'lineByLine',
        animationDuration: 1.35,
        kineticEffect: 'fadeIn',
        ...syncLine,
      },
    ],
    [
      'Luxury Title',
      'Elegant High Contrast Serif',
      {
        fontFamily: 'Playfair Display',
        fontWeight: 'bold',
        fontSize: 5.6,
        letterSpacing: 1.5,
        lineHeight: 1.3,
        wordsPerLine: 3,
        gradientEnabled: true,
        gradientColors: ['#FFD700', '#FFF8DC', '#FFD700'],
        strokeColor: '#422006',
        strokeWidthPercent: 5,
        shadowEnabled: true,
        shadowColor: 'rgba(66,32,6,0.5)',
        shadowBlur: 10,
        animationPreset: 'fadeUp',
        animationLogic: 'lineByLine',
        animationDuration: 1.15,
        ...syncLine,
      },
    ],
    [
      'Documentary Title',
      'Neutral Sans Serif',
      {
        fontFamily: 'Source Sans Pro',
        fontWeight: 'normal',
        fontSize: 4.9,
        letterSpacing: 0.4,
        lineHeight: 1.5,
        wordsPerLine: 5,
        color: '#D1D5DB',
        styleType: 'box',
        bgColor: 'rgba(0,0,0,0.68)',
        bgOpacity: 0.88,
        boxPaddingPercent: 30,
        boxCornerRadiusPercent: 4,
        animationPreset: 'fadeIn',
        animationLogic: 'lineByLine',
        animationDuration: 1.2,
        ...syncLine,
      },
    ],
    [
      'Bold Headline',
      'Extra Bold Sans Serif',
      {
        fontFamily: 'Montserrat',
        fontWeight: '900',
        fontSize: 6.2,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        lineHeight: 1.2,
        wordsPerLine: 3,
        color: '#FFFFFF',
        strokeColor: '#000000',
        strokeWidthPercent: 11,
        wordHighlightEnabled: true,
        wordHighlightMode: 'voiceSync',
        wordHighlightScale: 1.3,
        kineticEffect: 'scalePop',
        animationPreset: 'bounceIn',
        animationLogic: 'wordByWord',
        popScale: 1.2,
        ...syncWord,
      },
    ],
    [
      'Corporate Intro',
      'Geometric Sans Serif',
      {
        fontFamily: 'Outfit',
        fontWeight: '600',
        fontSize: 5,
        letterSpacing: 0.8,
        lineHeight: 1.35,
        wordsPerLine: 4,
        color: '#FFFFFF',
        styleType: 'box',
        bgColor: 'rgba(37,99,235,0.88)',
        bgOpacity: 0.92,
        boxPaddingPercent: 34,
        boxCornerRadiusPercent: 8,
        animationPreset: 'slideUp',
        animationLogic: 'lineByLine',
        animationDuration: 0.95,
        kineticEffect: 'slideFromBottom',
        kineticLogic: 'oneLine',
        ...syncLine,
      },
    ],
    [
      'Trailer Title',
      'Condensed Block Serif',
      {
        fontFamily: 'Roboto Slab',
        fontWeight: '900',
        fontSize: 6.5,
        letterSpacing: 1,
        textTransform: 'uppercase',
        lineHeight: 1.1,
        wordsPerLine: 2,
        color: '#FFFFFF',
        strokeColor: '#000000',
        strokeWidthPercent: 12,
        kineticEffect: 'scalePop',
        animationPreset: 'scaleIn',
        animationLogic: 'wordByWord',
        animationDuration: 0.75,
        popScale: 1.35,
        shadowEnabled: true,
        shadowColor: '#000000',
        shadowBlur: 8,
        ...syncKaraoke,
      },
    ],
    [
      'Premium Opening',
      'Modern Luxury Serif',
      {
        fontFamily: 'Cormorant Garamond',
        fontWeight: '600',
        fontSize: 5.8,
        letterSpacing: 2,
        lineHeight: 1.35,
        wordsPerLine: 3,
        gradientEnabled: true,
        gradientColors: ['#FAFAF9', '#E7E5E4', '#FFFFFF'],
        strokeColor: '#44403C',
        strokeWidthPercent: 4,
        shadowEnabled: true,
        shadowColor: 'rgba(255,215,0,0.35)',
        shadowBlur: 18,
        animationPreset: 'blurIn',
        animationLogic: 'lineByLine',
        animationDuration: 1.25,
        kineticEffect: 'glow',
        kineticLogic: 'oneLine',
        ...syncLine,
      },
    ],
  ]),
  typographyCat('subtitle-templates', '7. Subtitle Templates', [
    ['Clean Subtitle', 'Medium Sans Serif', { fontFamily: 'Roboto', fontWeight: '500', fontSize: 4.8, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 5, wordsPerLine: 5, lineHeight: 1.45, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Dynamic Subtitle', 'Bold Sans Serif', { fontFamily: 'Montserrat', fontWeight: 'bold', fontSize: 5.2, color: '#FFFFFF', strokeWidthPercent: 7, animationPreset: 'bounceIn', animationLogic: 'wordByWord', kineticEffect: 'scalePop', ...syncWord }],
    ['Highlight Subtitle', 'Bold + Highlight Words', { fontFamily: 'Montserrat', fontWeight: 'bold', fontSize: 5, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.45, color: '#FFFFFF', strokeWidthPercent: 6, animationPreset: 'wordByWord', animationLogic: 'wordByWord', ...syncWord }],
    ['Podcast Subtitle', 'Semi Bold Sans Serif', { fontFamily: 'Nunito', fontWeight: '600', fontSize: 4.9, styleType: 'box', bgColor: 'rgba(17,24,39,0.88)', bgOpacity: 0.9, boxPaddingPercent: 32, color: '#F3F4F6', lineHeight: 1.5, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Viral Subtitle', 'Heavy Sans Serif', { fontFamily: 'Anton', fontSize: 5.8, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 10, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.5, kineticEffect: 'scalePop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', popScale: 1.3, ...syncWord }],
    ['Smart Caption', 'Rounded Sans Serif', { fontFamily: 'Nunito', fontWeight: '600', fontSize: 5, color: '#FFFFFF', styleType: 'box', bgColor: 'rgba(0,0,0,0.78)', bgOpacity: 0.88, boxCornerRadiusPercent: 20, animationPreset: 'wordByWord', animationLogic: 'wordByWord', ...syncKaraoke }],
    ['Social Subtitle', 'Bold Rounded Sans', { fontFamily: 'Poppins', fontWeight: 'bold', fontSize: 5.1, styleType: 'box', bgColor: 'rgba(236,72,153,0.9)', bgOpacity: 0.92, boxCornerRadiusPercent: 24, color: '#FFFFFF', wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.25, ...syncWord }],
    ['Story Subtitle', 'Modern Serif', { fontFamily: 'Merriweather', fontWeight: 'normal', fontSize: 4.9, color: '#FEF3C7', strokeColor: '#1C1917', strokeWidthPercent: 4, lineHeight: 1.55, animationPreset: 'fadeUp', animationLogic: 'lineByLine', ...syncLine }],
    ['Focus Subtitle', 'Condensed Sans', { fontFamily: 'Oswald', fontWeight: 'bold', fontSize: 5.5, letterSpacing: 1, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.55, color: '#FBBF24', strokeWidthPercent: 7, wordsPerLine: 3, ...syncWord }],
    ['Auto Caption Pro', 'Bold Clean Sans', { fontFamily: 'Inter', fontWeight: 'bold', fontSize: 5, styleType: 'box', bgColor: 'rgba(0,0,0,0.82)', bgOpacity: 0.9, boxPaddingPercent: 28, color: '#FFFFFF', animationPreset: 'wordByWord', animationLogic: 'wordByWord', kineticEffect: 'fadeIn', ...syncKaraoke }],
  ]),
  typographyCat('kinetic-typography', '8. Kinetic Typography', [
    ['Word Pop', 'Heavy Rounded Sans', { fontFamily: 'Nunito', fontWeight: '900', fontSize: 5.4, kineticEffect: 'scalePop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', popScale: 1.4, color: '#FFFFFF', strokeWidthPercent: 8, ...syncWord }],
    ['Bounce Text', 'Bold Rounded', { fontFamily: 'Quicksand', fontWeight: 'bold', fontSize: 5.2, kineticEffect: 'scaleBounce', animationPreset: 'bounceIn', animationLogic: 'wordByWord', color: '#F472B6', strokeColor: '#000000', strokeWidthPercent: 6, ...syncWord }],
    ['Slide Text', 'Condensed Sans', { fontFamily: 'Oswald', fontWeight: 'bold', fontSize: 5.5, kineticEffect: 'slideFromLeft', animationPreset: 'slideRight', animationLogic: 'wordByWord', color: '#FFFFFF', strokeWidthPercent: 7, ...syncWord }],
    ['Typewriter', 'Monospace', { fontFamily: 'Courier New', fontWeight: 'bold', fontSize: 4.8, color: '#4ADE80', kineticEffect: 'typewriter', animationPreset: 'typewriter', animationLogic: 'charByChar', animationDuration: 1.1, ...syncKaraoke }],
    ['Text Reveal', 'Medium Sans', { fontFamily: 'Roboto', fontWeight: '500', fontSize: 5, animationPreset: 'lineReveal', animationLogic: 'lineByLine', kineticEffect: 'lineReveal', color: '#FFFFFF', strokeWidthPercent: 5, ...syncLine }],
    ['Dynamic Words', 'Extra Bold Sans', { fontFamily: 'Montserrat', fontWeight: '900', fontSize: 5.6, animationPreset: 'random', animationLogic: 'wordRandom', kineticEffect: 'random', colorLogic: 'perWord', color: '#FFFFFF', strokeWidthPercent: 9, ...syncWord }],
    ['Beat Sync Text', 'Heavy Condensed', { fontFamily: 'Bebas Neue', fontSize: 6, kineticEffect: 'pulse', kineticLogic: 'syncBeat', kineticLoop: true, animationPreset: 'pulse', animationLogic: 'wordByWord', color: '#FACC15', strokeWidthPercent: 8, ...syncWord }],
    ['Impact Words', 'Ultra Black Sans', { fontFamily: 'Anton', fontSize: 6.2, kineticEffect: 'scalePop', animationPreset: 'explode', animationLogic: 'wordByWord', popScale: 1.5, color: '#FF4444', strokeColor: '#FFFFFF', strokeWidthPercent: 10, ...syncWord }],
    ['Motion Caption', 'Geometric Sans', { fontFamily: 'Space Grotesk', fontWeight: 'bold', fontSize: 5, kineticEffect: 'float', kineticLoop: true, animationPreset: 'wave', animationLogic: 'wordByWord', color: '#A5F3FC', strokeWidthPercent: 5, ...syncWord }],
    ['Kinetic Pro', 'Mixed Weight Sans', { fontFamily: 'Roboto', fontWeight: '500', fontSize: 5, fontChangeLogic: 'oddEven', colorLogic: 'oddEven', animationPreset: 'wordByWord', animationLogic: 'wordByWord', kineticEffect: 'scalePop', wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.35, ...syncKaraoke }],
  ]),
  typographyCat('outline-stroke-styles', '9. Outline & Stroke Styles', [
    ['Bold Stroke', 'Heavy Sans + Stroke', { fontFamily: 'Impact', fontSize: 5.8, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 14, fontWeight: '900', animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['White Outline', 'Black Fill + White Stroke', { fontFamily: 'Montserrat', fontWeight: 'bold', fontSize: 5.2, color: '#000000', strokeColor: '#FFFFFF', strokeWidthPercent: 10, styleType: 'stroke', ...syncLine }],
    ['Black Outline', 'White Fill + Black Stroke', { fontFamily: 'Helvetica', fontWeight: 'bold', fontSize: 5.2, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 10, ...syncLine }],
    ['Neon Stroke', 'Rounded Sans + Glow', { fontFamily: 'Rubik', fontWeight: 'bold', fontSize: 5, color: '#39FF14', strokeColor: '#000000', strokeWidthPercent: 7, shadowEnabled: true, shadowColor: '#39FF14', shadowBlur: 22, kineticEffect: 'neon', kineticLoop: true, ...syncLine }],
    ['Double Outline', 'Extra Bold + Double Stroke', { fontFamily: 'Montserrat', fontWeight: '900', fontSize: 5.5, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 12, shadowEnabled: true, shadowColor: '#FFFFFF', shadowBlur: 2, shadowOffsetX: 2, shadowOffsetY: 2, ...syncLine }],
    ['Glow Stroke', 'Thick Sans + Glow', { fontFamily: 'Montserrat', fontWeight: '900', fontSize: 5.4, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 9, shadowEnabled: true, shadowColor: '#60A5FA', shadowBlur: 20, kineticEffect: 'glow', ...syncLine }],
    ['Thick Border', 'Ultra Black Sans', { fontFamily: 'Anton', fontSize: 6.5, color: '#FACC15', strokeColor: '#000000', strokeWidthPercent: 16, textTransform: 'uppercase', ...syncLine }],
    ['Premium Outline', 'Luxury Serif + Outline', { fontFamily: 'Playfair Display', fontWeight: 'bold', fontSize: 5.5, color: '#FFD700', strokeColor: '#422006', strokeWidthPercent: 6, letterSpacing: 1, ...syncLine }],
    ['Dynamic Stroke', 'Condensed Sans', { fontFamily: 'Oswald', fontWeight: 'bold', fontSize: 5.8, color: '#FFFFFF', strokeColor: '#DC2626', strokeWidthPercent: 9, kineticEffect: 'pulse', kineticLoop: true, animationPreset: 'pulse', animationLogic: 'wordByWord', ...syncWord }],
    ['Hero Outline', 'Giant Block Font', { fontFamily: 'Bebas Neue', fontSize: 7, color: '#FFFFFF', strokeColor: '#000000', strokeWidthPercent: 15, textTransform: 'uppercase', letterSpacing: 2, wordsPerLine: 2, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.15, ...syncWord }],
  ]),
  typographyCat('modern-ui-styles', '10. Modern UI Styles', [
    ['Search Bar', 'Google Style Sans', { fontFamily: 'Roboto', fontWeight: 'normal', fontSize: 4.6, styleType: 'box', bgColor: 'rgba(255,255,255,0.96)', bgOpacity: 0.98, color: '#374151', boxCornerRadiusPercent: 28, boxPaddingPercent: 48, positionY: 12, animationPreset: 'slideDown', animationLogic: 'lineByLine', ...syncLine }],
    ['Chat Message', 'App UI Sans', { fontFamily: 'Inter', fontWeight: '500', fontSize: 4.8, styleType: 'box', bgColor: 'rgba(59,130,246,0.92)', bgOpacity: 0.94, boxCornerRadiusPercent: 18, boxPaddingPercent: 34, color: '#FFFFFF', positionY: 72, animationPreset: 'slideUp', animationLogic: 'lineByLine', ...syncLine }],
    ['Notification Pop', 'Mobile UI Font', { fontFamily: 'Inter', fontWeight: '600', fontSize: 4.7, styleType: 'box', bgColor: 'rgba(255,255,255,0.97)', bgOpacity: 0.98, color: '#111827', boxCornerRadiusPercent: 14, boxPaddingPercent: 36, shadowEnabled: true, shadowBlur: 14, animationPreset: 'slideDown', animationLogic: 'lineByLine', ...syncLine }],
    ['Browser Window', 'Modern Interface Sans', { fontFamily: 'Helvetica', fontWeight: 'normal', fontSize: 4.8, styleType: 'box', bgColor: 'rgba(243,244,246,0.95)', bgOpacity: 0.96, color: '#1F2937', boxCornerRadiusPercent: 8, boxPaddingPercent: 40, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Mobile Screen', 'Clean Rounded Sans', { fontFamily: 'Nunito', fontWeight: '600', fontSize: 4.9, styleType: 'box', bgColor: 'rgba(0,0,0,0.75)', bgOpacity: 0.88, boxCornerRadiusPercent: 22, color: '#FFFFFF', boxPaddingPercent: 32, ...syncLine }],
    ['Voice Message', 'Soft Rounded Font', { fontFamily: 'Quicksand', fontWeight: '600', fontSize: 4.8, styleType: 'box', bgColor: 'rgba(34,197,94,0.85)', bgOpacity: 0.9, boxCornerRadiusPercent: 24, color: '#FFFFFF', animationPreset: 'fadeIn', animationLogic: 'wordByWord', ...syncWord }],
    ['Command Box', 'Monospace', { fontFamily: 'Fira Code', fontWeight: '500', fontSize: 4.6, styleType: 'box', bgColor: 'rgba(15,23,42,0.94)', bgOpacity: 0.96, color: '#22D3EE', boxCornerRadiusPercent: 6, boxPaddingPercent: 30, animationPreset: 'typewriter', animationLogic: 'charByChar', ...syncKaraoke }],
    ['Popup Alert', 'Bold UI Sans', { fontFamily: 'Montserrat', fontWeight: 'bold', fontSize: 5, styleType: 'box', bgColor: 'rgba(239,68,68,0.92)', bgOpacity: 0.94, color: '#FFFFFF', boxCornerRadiusPercent: 12, boxPaddingPercent: 36, kineticEffect: 'shake', animationPreset: 'bounceIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Text Bubble', 'Rounded Friendly Sans', { fontFamily: 'Poppins', fontWeight: '600', fontSize: 4.9, styleType: 'box', bgColor: 'rgba(255,255,255,0.94)', bgOpacity: 0.96, color: '#1F2937', boxCornerRadiusPercent: 26, boxPaddingPercent: 34, positionY: 68, ...syncLine }],
    ['Digital Interface', 'Futuristic Sans', { fontFamily: 'Space Grotesk', fontWeight: '600', fontSize: 4.9, color: '#67E8F9', strokeColor: '#0E7490', strokeWidthPercent: 5, styleType: 'box', bgColor: 'rgba(8,47,73,0.85)', bgOpacity: 0.88, boxCornerRadiusPercent: 6, animationPreset: 'blurIn', animationLogic: 'lineByLine', ...syncLine }],
  ]),
  typographyCat('news-documentary', '11. News & Documentary', [
    ['Breaking News', 'Bold Condensed Sans', { fontFamily: 'Oswald', fontWeight: 'bold', fontSize: 5.8, textTransform: 'uppercase', color: '#FFFFFF', styleType: 'box', bgColor: 'rgba(220,38,38,0.94)', bgOpacity: 0.96, boxPaddingPercent: 28, letterSpacing: 1.5, animationPreset: 'slideLeft', animationLogic: 'lineByLine', ...syncLine }],
    ['News Lower Third', 'Broadcast Sans', { fontFamily: 'Helvetica', fontWeight: 'bold', fontSize: 4.8, styleType: 'box', bgColor: 'rgba(0,0,0,0.85)', bgOpacity: 0.92, color: '#FFFFFF', boxPaddingPercent: 26, positionY: 85, animationPreset: 'slideUp', animationLogic: 'lineByLine', ...syncLine }],
    ['Reporter Name Tag', 'Semi Bold Sans', { fontFamily: 'Source Sans Pro', fontWeight: '600', fontSize: 4.6, styleType: 'box', bgColor: 'rgba(255,255,255,0.92)', bgOpacity: 0.95, color: '#111827', boxPaddingPercent: 22, boxCornerRadiusPercent: 4, positionY: 82, ...syncLine }],
    ['Documentary Label', 'Clean Modern Sans', { fontFamily: 'Inter', fontWeight: '500', fontSize: 4.7, color: '#E5E7EB', styleType: 'box', bgColor: 'rgba(0,0,0,0.65)', bgOpacity: 0.85, boxPaddingPercent: 24, letterSpacing: 0.8, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Fact Display', 'Medium Sans', { fontFamily: 'Roboto', fontWeight: '500', fontSize: 4.9, styleType: 'box', bgColor: 'rgba(30,58,138,0.88)', bgOpacity: 0.9, color: '#FFFFFF', boxPaddingPercent: 32, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Information Card', 'Geometric Sans', { fontFamily: 'Outfit', fontWeight: '600', fontSize: 4.8, styleType: 'box', bgColor: 'rgba(241,245,249,0.94)', bgOpacity: 0.96, color: '#0F172A', boxCornerRadiusPercent: 10, boxPaddingPercent: 34, ...syncLine }],
    ['Timeline Text', 'Thin Sans', { fontFamily: 'Inter', fontWeight: '300', fontSize: 4.6, color: '#D1D5DB', letterSpacing: 1.2, strokeWidthPercent: 3, strokeColor: '#374151', animationPreset: 'fadeIn', animationLogic: 'lineByLine', animationDuration: 1.3, ...syncLine }],
    ['News Flash', 'Ultra Bold Sans', { fontFamily: 'Anton', fontSize: 6, textTransform: 'uppercase', color: '#FEF08A', strokeColor: '#000000', strokeWidthPercent: 9, kineticEffect: 'flash', kineticLoop: true, animationPreset: 'zoomIn', animationLogic: 'wordByWord', ...syncWord }],
    ['Headline Banner', 'Black Condensed', { fontFamily: 'Bebas Neue', fontSize: 6.2, textTransform: 'uppercase', styleType: 'box', bgColor: 'rgba(0,0,0,0.92)', bgOpacity: 0.96, color: '#FFFFFF', boxPaddingPercent: 30, letterSpacing: 2, wordsPerLine: 3, ...syncLine }],
    ['TV Broadcast', 'Broadcast Typeface', { fontFamily: 'Arial Black', fontSize: 5.2, color: '#FFFFFF', styleType: 'box', bgColor: 'rgba(17,24,39,0.9)', bgOpacity: 0.94, boxPaddingPercent: 28, strokeWidthPercent: 4, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
  ]),
  typographyCat('luxury-premium', '12. Luxury & Premium', [
    ['Gold Luxury', 'High Contrast Serif', { fontFamily: 'Playfair Display', fontWeight: 'bold', fontSize: 5.6, gradientEnabled: true, gradientColors: ['#FFD700', '#FFF8DC', '#FFD700'], strokeColor: '#422006', strokeWidthPercent: 5, letterSpacing: 1.2, animationPreset: 'fadeUp', animationLogic: 'lineByLine', ...syncLine }],
    ['Diamond Text', 'Fashion Serif', { fontFamily: 'Playfair Display', fontWeight: 'bold', fontSize: 5.4, color: '#E0F2FE', strokeColor: '#0369A1', strokeWidthPercent: 4, shadowEnabled: true, shadowColor: '#7DD3FC', shadowBlur: 16, letterSpacing: 2, ...syncLine }],
    ['Royal Serif', 'Classic Serif', { fontFamily: 'Georgia', fontWeight: 'bold', fontSize: 5.3, color: '#FDE68A', strokeColor: '#78350F', strokeWidthPercent: 5, letterSpacing: 1, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Fashion Title', 'Vogue Style Serif', { fontFamily: 'Playfair Display', fontWeight: 'bold', fontSize: 5.8, textTransform: 'uppercase', letterSpacing: 4, color: '#FFFFFF', strokeWidthPercent: 3, strokeColor: '#000000', lineHeight: 1.2, wordsPerLine: 3, ...syncLine }],
    ['Premium Brand', 'Elegant Sans', { fontFamily: 'Inter', fontWeight: '300', fontSize: 5.2, letterSpacing: 3, color: '#F5F5F4', strokeWidthPercent: 3, strokeColor: '#44403C', animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Elegant Caption', 'Thin Luxury Serif', { fontFamily: 'Cormorant Garamond', fontWeight: '300', fontSize: 5.4, color: '#FAFAF9', strokeColor: '#57534E', strokeWidthPercent: 3, letterSpacing: 1.5, lineHeight: 1.5, ...syncLine }],
    ['Magazine Cover', 'Editorial Serif', { fontFamily: 'Newsreader', fontWeight: 'bold', fontSize: 5.6, textTransform: 'uppercase', letterSpacing: 2, color: '#111827', styleType: 'box', bgColor: '#FAFAF9', bgOpacity: 0.96, boxPaddingPercent: 36, ...syncLine }],
    ['Luxury Minimal', 'Thin Sans', { fontFamily: 'Inter', fontWeight: '300', fontSize: 4.8, letterSpacing: 2.5, color: '#E7E5E4', strokeWidthPercent: 2, strokeColor: '#78716C', lineHeight: 1.5, ...syncLine }],
    ['Prestige Text', 'Premium Serif', { fontFamily: 'EB Garamond', fontWeight: '600', fontSize: 5.5, color: '#FFD700', strokeColor: '#1C1917', strokeWidthPercent: 4, shadowEnabled: true, shadowColor: 'rgba(255,215,0,0.3)', shadowBlur: 12, ...syncLine }],
    ['Elite Typography', 'Serif + Small Caps', { fontFamily: 'Cinzel', fontWeight: 'bold', fontSize: 5.4, textTransform: 'uppercase', letterSpacing: 3, color: '#F5F5DC', strokeColor: '#292524', strokeWidthPercent: 5, gradientEnabled: true, gradientColors: ['#D6D3D1', '#FFFFFF', '#D6D3D1'], ...syncLine }],
  ]),
  typographyCat('gaming-tech', '13. Gaming & Tech', [
    ['Cyber Text', 'Futuristic Tech Font', { fontFamily: 'Orbitron', fontWeight: 'bold', fontSize: 5.2, color: '#22D3EE', strokeColor: '#000000', strokeWidthPercent: 7, shadowEnabled: true, shadowColor: '#06B6D4', shadowBlur: 16, kineticEffect: 'glitch', kineticLoop: true, ...syncWord }],
    ['HUD Interface', 'Digital Sans', { fontFamily: 'Share Tech', fontSize: 4.8, color: '#4ADE80', strokeColor: '#14532D', strokeWidthPercent: 5, styleType: 'box', bgColor: 'rgba(0,0,0,0.72)', bgOpacity: 0.85, boxCornerRadiusPercent: 4, animationPreset: 'fadeIn', animationLogic: 'lineByLine', ...syncLine }],
    ['Gaming Overlay', 'Bold Gaming Font', { fontFamily: 'Russo One', fontSize: 5.6, color: '#FFFFFF', strokeColor: '#7C3AED', strokeWidthPercent: 9, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.4, kineticEffect: 'scalePop', animationPreset: 'bounceIn', animationLogic: 'wordByWord', ...syncWord }],
    ['Glitch Title', 'Distorted Sans', { fontFamily: 'Rubik Glitch', fontSize: 5.4, color: '#F0ABFC', strokeColor: '#000000', strokeWidthPercent: 6, kineticEffect: 'glitch', kineticLoop: true, animationPreset: 'random', animationLogic: 'wordRandom', ...syncWord }],
    ['Sci Fi Caption', 'Futuristic Condensed', { fontFamily: 'Exo 2', fontWeight: 'bold', fontSize: 5.3, letterSpacing: 1, color: '#C4B5FD', strokeColor: '#4C1D95', strokeWidthPercent: 6, animationPreset: 'slideUp', animationLogic: 'wordByWord', ...syncWord }],
    ['Tech Display', 'Digital Display Font', { fontFamily: 'Audiowide', fontSize: 5, color: '#39FF14', strokeColor: '#000000', strokeWidthPercent: 8, shadowEnabled: true, shadowColor: '#39FF14', shadowBlur: 14, kineticEffect: 'neon', kineticLoop: true, ...syncLine }],
    ['Digital Scan', 'Monospace Tech', { fontFamily: 'Fira Code', fontWeight: '500', fontSize: 4.7, color: '#00FF88', styleType: 'box', bgColor: 'rgba(0,20,10,0.88)', bgOpacity: 0.9, boxCornerRadiusPercent: 2, animationPreset: 'typewriter', animationLogic: 'charByChar', ...syncKaraoke }],
    ['RGB Motion', 'Heavy Sans', { fontFamily: 'Montserrat', fontWeight: '900', fontSize: 5.5, gradientEnabled: true, gradientColors: ['#FF0080', '#7928CA', '#00DFD8'], strokeColor: '#000000', strokeWidthPercent: 7, kineticEffect: 'colorPop', animationPreset: 'wordByWord', animationLogic: 'wordByWord', colorLogic: 'perWord', ...syncWord }],
    ['Hologram Text', 'Sci Fi Typeface', { fontFamily: 'Orbitron', fontWeight: 'bold', fontSize: 5.2, color: 'rgba(103,232,249,0.92)', strokeColor: '#0891B2', strokeWidthPercent: 4, shadowEnabled: true, shadowColor: '#22D3EE', shadowBlur: 24, kineticEffect: 'glow', kineticLoop: true, wordHighlightEnabled: true, wordHighlightMode: 'voiceSync', wordHighlightScale: 1.2, ...syncWord }],
    ['Futuristic UI', 'Neo Geometric Sans', { fontFamily: 'Space Grotesk', fontWeight: 'bold', fontSize: 5, color: '#E0E7FF', strokeColor: '#4338CA', strokeWidthPercent: 5, styleType: 'box', bgColor: 'rgba(30,27,75,0.88)', bgOpacity: 0.9, boxCornerRadiusPercent: 8, textBgEnabled: true, textBgCategory: 'neon', textBgPatternId: 'neon_blue', textBgOpacity: 0.5, animationPreset: 'blurIn', animationLogic: 'lineByLine', ...syncLine }],
  ]),
]

export const ALL_CAPTION_TEXT_PRESETS = CAPTION_TEXT_PRESET_CATEGORIES.flatMap((c) => c.presets)

export function getCaptionTextPresetById(id) {
  return ALL_CAPTION_TEXT_PRESETS.find((p) => p.id === id) || null
}

export function applyCaptionTextPresetPatch(overlay, preset) {
  if (!preset?.patch) return overlay
  const { _captionSync, ...overlayPatch } = preset.patch
  return { ...overlay, ...overlayPatch }
}
